#!/bin/bash

domain_information() {
    local domain="$1"
    local subdomain="$2"
    local line
    line=$(dig "$subdomain"."$domain" +short)
    echo "The subdomain $subdomain is a $(get_record_type "$line") record and points to $line"
}

get_record_type() {
    local line="$1"
    if [[ $line =~ ":" ]]; then
        echo "CNAME"
    else
        echo "A"
    fi
}

domain="$1"
subdomain="$2"

if [ -z "$subdomain" ]; then
    domain_information "$domain" "www"
    domain_information "$domain" "lb-01"
    domain_information "$domain" "web-01"
    domain_information "$domain" "web-02"
else
    domain_information "$domain" "$subdomain"
fi
