#!/usr/bin/env bash
# configures a new HAproxy as a load balancer

# Install HAproxy on a server
apt-get -y update
apt-get -y install haproxy=1.6.\*

# Configure haproxy configuration file to distribute requests using a roundrobin algorithm
echo '
frontend mikeowusu.tech
        bind 0:80
        default_backend web_servers

backend web_servers
        balance roundrobin
        server 196560-web-01 54.174.70.122
        server 196560-web-02 34.201.174.248
' >> /etc/haproxy/haproxy.cfg

# Restart HAproxy service
service haproxy restart
